### ISSUE TITLE
`swift main.swift`运行报错`JIT session error: Symbols not found`

### ISSUE THREAD

**Issue by Urie96** [wmszhe/mac_ocr#1]
大佬你好，我是从[Raycast代码](https://github.com/raycast/script-commands/blob/master/commands/system/ocr.swift)找过来的，我看他那里面应该是可以不编译直接跑的，但是我直接跑会报错`JIT session error: Symbols not found: [ _OBJC_CLASS_$_NSPasteboard, _NSPasteboardTypeString ]
Failed to materialize symbols: { (main, { _$sSo22VNRecognizeTextRequestCML, _symbolic ______ypt So13VNImageOptiona, _$sS2Ss21_ObjectiveCBridgeable10FoundationWL, _$sSo16NS....此处省略一大片`，M1芯片，macos 14.3。但我运行你这个仓库里编译好的二进制文件是没问题的。我自己对swift完全不懂，所以请教一下能不能不编译直接跑呢？

**Comment by wmszhe** [comment]
抱歉，我这里没有m芯片的mac

如果使用编译好的二进制没有问题的话，可以直接在 Raycast 里使用二进制运行

Raycast里Create Script Command，Template 选 bash，然后 Create Script

然后编辑生成的 sh 文件，替换 echo "Hello World!" 为

cd "you_mac_ocr_parent_path/" && ./mac_ocr

这样要比执行 swift 脚本快的多。执行 swift 脚本实际上每次都是编译运行的

**Comment by wmszhe** [comment]
给你个示例：

```sh
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title OCR
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 🖼
# @raycast.packageName OCR

# Documentation:
# @raycast.description mac ocr
# @raycast.author wmszhe

cd "/Users/wmszhe/Developer/tools/" && ./mac_ocr
```

**Comment by Urie96** [comment]
嗯嗯，谢谢建议，swift脚本有时候的确很慢，我会换成直接执行二进制。关于swift脚本报错我后面搞清楚了是swift的bug，他们在仓库里已经修复了。另外比较好奇为啥你用x86的编译出来的mac_ocr，我用arm也能跑呢。还有为啥我m1的能识别中文，但是公司的intel macbook的就不行，是不是系统有啥配置没配呢？

**Comment by wmszhe** [comment]
let recognitionLanguages = ["zh-Hans", "zh-Hant", "en-US", "ja-JP"]

可以尝试改下这个

**Comment by Urie96** [comment]
> let recognitionLanguages = ["zh-Hans", "zh-Hant", "en-US", "ja-JP"]
> 
> 可以尝试改下这个

可以了，非常感谢😊
